name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      # Build (compile & package) but skip tests
      - name: Build without tests
        run: mvn -B clean install -DskipTests

      # Run just the tests
      - name: Run tests
        run: mvn test
